version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - db
    environment:
      # set to 1 connection to the arbitrary server will be allowed
      - PMA_ARBITRARY=1
      #define address/host name of the MySQL server
      - PMA_HOST=${MYSQL_CONTAINER_NAME}
      - PMA_PORT=${MYSQL_DOCKER_PORT}
    ports:
      - "8888:80"
  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "${MYSQL_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: